# Generated by Django 3.1.1 on 2020-09-17 06:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_auto_20200916_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_likes',
        ),
        migrations.AddField(
            model_name='course',
            name='course_likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
