# Generated by Django 3.1.1 on 2020-09-17 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('user', 'course', 'value')},
        ),
    ]
