# Generated by Django 3.1.1 on 2020-09-18 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0008_delete_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
