# Generated by Django 3.1.1 on 2020-09-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20200918_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='course_rating',
            field=models.FloatField(),
        ),
    ]
